steps:
  - id: fecth-npm-token-from-secret-manager
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        NPM_TOKEN="$( gcloud secrets versions access latest --secret=NPM_TOKEN )" &&
        echo $NPM_TOKEN &&
        echo "NPM_TOKEN=${NPM_TOKEN}" > /workspace/.env &&
        cat /workspace/.env
  - id: install-dependencies
    args: [ 'install' ]
    name: node:alpine
    entrypoint: yarn
  - id: build-package-dist
    args: [ 'build' ]
    name: node:alpine
    entrypoint: yarn
  - id: publish-to-registry
    name: node:alpine
    entrypoint: sh
    args:
    - -c
    - |
      cat /workspace/.env &&
      source /workspace/.env &&
      env &&
      npm publish
