steps:
  - id: fecth-npm-token-from-secret-manager
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - echo "_auth=$( gcloud secrets versions access latest --secret=NPM_TOKEN --format='get(payload.data)' | tr '_-' '/+' | base64 -d )" >> .npmrc
  - id: install-dependencies-and-publish-package
    name: node:alpine
    entrypoint: sh
    args:
      - -c
      - yarn install && npm publish --access public
